<?php

namespace Sch\MainBundle\Repository;

/**
 * OrderModesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderModesRepository extends \Doctrine\ORM\EntityRepository
{
}
