<?php

namespace Sch\MainBundle\Repository;

/**
 * ProductLineTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLineTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
