<?php

namespace Sch\MainBundle\Repository;

/**
 * ProductLinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLinesRepository extends \Doctrine\ORM\EntityRepository
{
}
