<?php

namespace Sch\MainBundle\Repository;

/**
 * ProductTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
