<?php

namespace Sch\MainBundle\Repository;

/**
 * RetailerTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
