<?php

namespace Sch\MainBundle\Repository;

/**
 * RetailerCountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerCountriesRepository extends \Doctrine\ORM\EntityRepository
{
}
