<?php

namespace Sch\MainBundle\Repository;

/**
 * TwilioLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwilioLogRepository extends \Doctrine\ORM\EntityRepository
{
}
