<?php

namespace Sch\MainBundle\Repository;

/**
 * UserPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhoneRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * 
    * get phone based on users
    * It is used to fetch data from database on given filters.
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
    public function getPhones($value = null)
    {
        $query = $this->createQueryBuilder('up')
                            ->select('up.phone')
                            ->innerJoin('MainBundle:User', 'u', 'WITH', 'u.id = up.user')
                            ->andWhere('up.user = :user')
                                    ->setParameter('user', $value['id']);
                                
        
                                
        $result = $query->getQuery()->getResult();
        return $result;
    }
	/**
    * 
    * check
    * It is used to check if data is valid or not based on the filters.
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
	public function check($value = null)
	{
		$query = $this->createQueryBuilder('up')
                            ->select('u.name as User')
                            ->addSelect('up.phone as Phone')
                            ->innerJoin('MainBundle:User', 'u', 'WITH', 'u.id = up.user')
                            ->andWhere('u.name = :uname')
        							->setParameter('uname', $value['user'])
                            ->andWhere('up.phone = :uphone')
                            ->setParameter('uphone', $value['phone']);
                            // ->andWhere('u.status != :ustatus')
                            //         ->setParameter('ustatus', 'Used' );
        						
    	$result = $query->getQuery()->getResult();
    	return $result;
	}
	
}

