<?php

namespace Sch\MainBundle\Repository;

/**
 * UserPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Saswati
 *
 * @category Repository
 */
class UserPhoneRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * 
    * get phone number based on users
    * It is used to fetch data from database on given filters.
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
    public function getPhones($value = null)
    {
        $query = $this->createQueryBuilder('up')
                    ->select('up.phone')
                    ->addSelect('up.status')
                    ->innerJoin('MainBundle:User', 'u', 'WITH', 'u.id = up.user')
                    ->andWhere('up.user = :user')
                        ->setParameter('user', $value['id']);

        return $query->getQuery()->getResult();
    }
	/**
    * 
    * check
    * It is used to check if data is valid or not based on the filters.
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
	public function check($value = null)
	{
		$query = $this->createQueryBuilder('up')
                    ->select('u.name as User')
                    ->addSelect('up.phone as Phone')
                    ->innerJoin('MainBundle:User', 'u', 'WITH', 'u.id = up.user')
                    ->andWhere('u.name = :uname')
						->setParameter('uname', $value['user'])
                    ->andWhere('up.phone = :uphone')
                    ->setParameter('uphone', $value['phone']);

        return $query->getQuery()->getResult();
	}
	
}

