main_homepage:
    path: /hello/{name}
    defaults: { _controller: MainBundle:Default:index }

sch_main_api_test:
    path: /api/test
    defaults: { _controller: MainBundle:ApiTest:apiTest }

sch_main_search_details:
    path: /api/getRevenue
    defaults: { _controller: MainBundle:Revenue:getRevenueDetail }

