main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
app:
  resource: '@MainBundle/Controller/'
  type: annotation
  prefix: /api
  defaults:
    _format: json
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc