# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
services:
    # ...
    twilio.client:
        class: Twilio\Rest\Client
        arguments: ['%twilio_sid%', '%twilio_token%']
        
    # app.exception_listener:
    #     class: Sch\MainBundle\EventListener\ExceptionListener
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.exception }

    app.request_listener:
        class: Sch\MainBundle\EventListener\RequestListener
        arguments: [ @sch_main.auth, @translator ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }