<?php

namespace Proxies\__CG__\Sch\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Revenue extends \Sch\MainBundle\Entity\Revenue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'id', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkProducts', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkRetailerCountry', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkRetailerType', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkOrderMode', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'year', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'quarter', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'revenue', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'quantity', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'grossMargin'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'id', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkProducts', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkRetailerCountry', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkRetailerType', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'fkOrderMode', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'year', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'quarter', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'revenue', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'quantity', '' . "\0" . 'Sch\\MainBundle\\Entity\\Revenue' . "\0" . 'grossMargin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Revenue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkProducts($fkProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkProducts', [$fkProducts]);

        return parent::setFkProducts($fkProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkProducts', []);

        return parent::getFkProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkRetailerCountry($fkRetailerCountry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkRetailerCountry', [$fkRetailerCountry]);

        return parent::setFkRetailerCountry($fkRetailerCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkRetailerCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkRetailerCountry', []);

        return parent::getFkRetailerCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkRetailerType($fkRetailerType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkRetailerType', [$fkRetailerType]);

        return parent::setFkRetailerType($fkRetailerType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkRetailerType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkRetailerType', []);

        return parent::getFkRetailerType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkOrderMode($fkOrderMode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkOrderMode', [$fkOrderMode]);

        return parent::setFkOrderMode($fkOrderMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkOrderMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkOrderMode', []);

        return parent::getFkOrderMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuarter($quarter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuarter', [$quarter]);

        return parent::setQuarter($quarter);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuarter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuarter', []);

        return parent::getQuarter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevenue($revenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevenue', [$revenue]);

        return parent::setRevenue($revenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenue', []);

        return parent::getRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrossMargin($grossMargin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrossMargin', [$grossMargin]);

        return parent::setGrossMargin($grossMargin);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrossMargin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrossMargin', []);

        return parent::getGrossMargin();
    }

}
